### ISSUE TITLE
git clone 到本地，yarn install后 npm start 报错

### ISSUE THREAD

**Issue by CrzMarvin** [welearnmore/WLM-TypeScript-React-Starter#7]
复现：
git clone https://github.com/icepy/typescript-react-starter.git
cd typescript-react-starter
yarn install
yarn start

页面报错:
```
./src/store/index.ts
Cannot find file: 'flow.ts' does not match the corresponding name on disk: './src/pages/home/Home'.
```
node version: 10.13.0

**Comment by ming2281** [comment]
> 复现：
> git clone https://github.com/icepy/typescript-react-starter.git
> cd typescript-react-starter
> yarn install
> yarn start
> 
> 页面报错:
> 
> ```
> ./src/store/index.ts
> Cannot find file: 'flow.ts' does not match the corresponding name on disk: './src/pages/home/Home'.
> ```
> 
> node version: 10.13.0

您解决此问题了吗?

我也遇到了同样的问题

Failed to compile
./src/store/index.ts
Cannot find file: 'flow.ts' does not match the corresponding name on disk: '.\src\pages\home\Home'.

**Comment by prolland006** [comment]
"home" have to be set to "Home" but I have another error after : 
<pre>TypeScript error in /home/patrice/dvt/react/sandbox/typescript-react-starter/node_modules/jest-diff/build/diffLines.d.ts(8,13):
'=' expected.  TS1005

     6 |  */
     7 | import { Diff } from './cleanupSemantic';
  >  8 | import type { DiffOptions } from './types';</pre>

**Comment by prolland006** [comment]
just put typescript@3.8.2 and it is corrected

**Comment by icepy** [comment]
@hezhiming @CrzMarvin 

建议不要再使用这个项目，这个项目是在很早期 CRA 没有提供配置 typescript 时做的，现在 CRA 已经提供了 typescript 的模板，自行安装就行，`npx create-react-app project_name --template typescript`

**Comment by icepy** [comment]
@prolland006 

recommended to use create-react-app

```bash
$ npx create-react-app [your project name]  --template typescript
```
